Update aioclash

diff --git a/aioclash b/aioclash
--- a/aioclash
+++ b/aioclash
@@ -33,6 +33,10 @@ gateway=$(cat /etc/network/interfaces |grep gateway | awk '{print $2}' | head -n
 local_ip=$(ip a 2>&1 | grep -w 'inet' | grep 'global' | grep -E '\ 1(92|0|72|00|1)\.' | sed 's/.*inet.//g' | sed 's/\/[0-9][0-9].*$//g' | head -n 1);
 eth_n=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
 
+CLASH_PATH="/srv/clash"
+clash_bin="/usr/bin/clash"
+clash_version_file="${CLASH_PATH}/version_clash"
+
 webget2(){
     #参数【$1】代表下载目录，【$2】代表在线地址
     #参数【$3】代表输出显示，【$4】不启用重定向
@@ -950,48 +954,6 @@ EOF
     echo -e "${green}软件安装完成!${end}"
 }
 
-# install_clash() {
-#     #new_clash_ver=$( wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep clash_v | awk '{print $2}')
-#     new_clash_ver=$(cat /srv/version  | grep clash_v | awk '{print $2}')
-#     if [[ ! -n "$new_clash_ver" ]]; then
-#       echo -e "${red}Clash检测版本失败!${end}"
-#       exit 1
-#     fi      
-#     if [ ! -d "/tmp/clash" ]; then
-#       mkdir /tmp/clash
-#     fi 
-#     webget2 /tmp/clash/clash.gz "${url_cdn}https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-${cpucore}-${new_clash_ver}.gz"
-#     if [[ $? -ne 0 ]]; then
-#       echo -e "${red}Clash下载失败!${end}"
-#       exit 1
-#     fi
-#       echo -e "${green}Clash下载成功!${end}" 
-#     rm -rf /usr/bin/clash
-#     gunzip /tmp/clash/clash.gz
-#     mv /tmp/clash/clash /usr/bin/clash
-#     chmod +x /usr/bin/clash
-#     setcap cap_net_bind_service=+ep /usr/bin/clash
-#     webget2  /tmp/clash/dashboard.zip  ${url_cdn}https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip
-#     if [[ $? -ne 0 ]]; then
-#       echo -e "${red}Dashboard下载失败!${end}"
-#       exit 1
-#     fi
-#     echo -e "${green}Dashboard下载成功!${end}" 
-#     if [ ! -d "/srv/clash" ]; then
-#       mkdir /srv/clash
-#     fi 
-#     webget2 /srv/clash/Country.mmdb ${url_cdn}https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
-#     cd /tmp/clash
-#     unzip dashboard.zip >> /dev/null 2>&1
-#     mv -f -T /tmp/clash/clash-dashboard-gh-pages /srv/clash/dashboard
-#     rm -rf /tmp/clash
-#     supervisor_clash_config
-#     supervisorctl update >> /dev/null 2>&1
-#     supervisorctl restart clash >> /dev/null 2>&1
-#     echo -e "${green}Clash安装成功!${end}"
-#     # echo -e "${green}Clash初始化!${end}" &&sleep 30
-# }
-
 install_clash() {
     clash_premium_url="https://api.github.com/repos/Dreamacro/clash/releases/tags/premium"
 
@@ -1054,28 +1016,77 @@ install_clash() {
 }
 
 update_clash_y() {
-    #new_clash_ver=$( wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep clash_v | awk '{print $2}')
-    new_clash_ver=$(cat /srv/version  | grep clash_v | awk '{print $2}')
-    if [[ ! -n "$new_clash_ver" ]]; then
-      echo -e "${red}Clash检测版本失败!${end}"
-      exit 1
-    fi  
-    if [ ! -d "/tmp/clash" ]; then
-      mkdir /tmp/clash
-    fi            
-    webget2 /tmp/clash/clash.gz "${url_cdn}https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-${cpucore}-${new_clash_ver}.gz"
-    if [[ $? -ne 0 ]]; then
-      echo -e "${red}Clash下载失败!${end}"
+    if [ ! -f "${clash_bin}" ]; then
+      echo "1970.01.01" > ${clash_version_file}
+    fi
+
+    if [ ! -f "${clash_version_file}" ]; then
+      echo $(${clash_bin} -v 2>/dev/null | awk '{print $2}') > ${clash_version_file}
+    fi
+    local_clash_version=$(cat "${clash_version_file}")
+
+    #date -d "${local_clash_version}-00:00" +%s
+    echo "Locale Clash Premium: ${local_clash_version}."
+    # echo "Please download the latest version from https://github.com/Dreamacro/clash/releases/tag/premium manually."
+
+    [ -f /tmp/clash_premium_release.json ] && rm /tmp/clash_premium_release.json
+    curl -s -o /tmp/clash_premium_release.json https://api.github.com/repos/Dreamacro/clash/releases/tags/premium
+    if [ ! -f /tmp/clash_premium_release.json ]; then
+      echo "Failed to get the release information of Clash Premium."
       exit 1
     fi
-    echo -e "${green}Clash下载成功!${end}" 
-    rm -rf /usr/bin/clash
-    gunzip /tmp/clash/clash.gz
-    mv /tmp/clash/clash /usr/bin/clash
-    chmod +x /usr/bin/clash
-    rm -rf /tmp/clash
-    supervisorctl restart clash >> /dev/null 2>&1
-    echo -e "${green}升级Clash成功，请重新运行脚本!${end}" && exit 0
+
+    remote_clash_version=$(jq '.name' /tmp/clash_premium_release.json | tr -d '"' | awk '{print $2}')
+    if [ $(echo ${local_clash_version} | tr -d ".") -ge $(echo ${remote_clash_version} | tr -d ".") ]; then
+      echo "Clash Premium ${local_clash_version} is up to date."
+      exit 2
+    else
+      echo "Found a new version of Clash Premium ${remote_clash_version}."
+    fi
+
+    [ -f /tmp/clash_premium_release_assets ] && rm /tmp/clash_premium_release_assets
+    jq '.assets[].name' /tmp/clash_premium_release.json > /tmp/clash_premium_release_assets
+    if [ ! -f /tmp/clash_premium_release_assets ]; then
+      echo "Failed to get the release information of Clash Premium."
+      rm /tmp/clash_premium_release.json
+      exit 1
+    fi
+
+    i=0
+    while read line ; do
+      l=$(echo $line | grep "${cpucore}")
+      if [ ! -z $l ]; then
+        break
+      fi
+      i=$(( i+1 ))
+    done < /tmp/clash_premium_release_assets
+
+    rm /tmp/clash_premium_release_assets
+    remote_clash_download_url=$(jq ".assets[${i}].browser_download_url" /tmp/clash_premium_release.json | tr -d '"')
+    rm /tmp/clash_premium_release.json 
+    echo "Start downloading Clash Premium ${remote_clash_version} from ${remote_clash_download_url}..."
+    [ -f "${CLASH_PATH}/clash.gz" ] && rm "${CLASH_PATH}/clash.gz"
+    curl -L -# -o "${CLASH_PATH}/clash.gz" "https://git.o8.cx/${remote_clash_download_url}"
+    if [ ! -f "${CLASH_PATH}/clash.gz" ]; then
+      echo "Failed to download Clash Premium."
+      echo "Please download and upload it to ${CLASH_PATH} manually."
+      exit 1
+    fi
+    [ -f ${CLASH_PATH}/clash.old ] && rm ${CLASH_PATH}/clash.old
+    [ -f ${clash_bin} ] && mv ${clash_bin} ${CLASH_PATH}/clash.old
+    gzip -d "${CLASH_PATH}/clash.gz" && chmod +x ${clash_bin} && ${clash_bin} -v
+    if [ $? -eq 1 ]; then
+      echo "Failed to download Clash Premium."
+      echo "Please try to re-run this script to download it again."
+      [ -f ${CLASH_PATH}/clash.gz ] && rm "${CLASH_PATH}/clash.gz"
+      [ -f ${clash_bin} ] && rm ${clash_bin}
+      mv ${CLASH_PATH}/clash.old ${clash_bin}
+      exit 1
+    fi
+    new_clash_version=$(${clash_bin} -v 2>/dev/null | awk '{print $2}')
+
+    echo ${new_clash_version} > ${clash_version_file}
+    echo "Clash Premium has been updated to ${new_clash_version}."
 }
 
 update_clash() {
