Update aioclash

diff --git a/aioclash b/aioclash
--- a/aioclash
+++ b/aioclash
@@ -71,6 +71,13 @@ webget2(){
     fi
 }
 
+verlte() {
+    [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
+}
+verlt() {
+    [ "$1" = "$2" ] && return 1 || verlte $1 $2
+}
+
 # check root
 [[ $EUID -ne 0 ]] && echo -e "${red}错误:  必须使用root用户运行此脚本!\n${end}" && exit 1
 
@@ -1110,34 +1117,6 @@ update_clash_y() {
     echo -e "${green}Clash Premium has been updated to ${new_clash_version}.${end}"
 }
 
-update_clash() {
-    #new_clash_ver=$( wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep clash_v | awk '{print $2}')
-    new_clash_ver=$(cat /srv/version  | grep clash_v | awk '{print $2}')
-    now_clash_ver=$(clash -v | awk '{print $2}')
-    if [[ "${now_clash_ver}" != "${new_clash_ver}" ]]  ;then
-      echo -e "Clash已有新版本: ${new_clash_ver}，当前版本:${now_clash_ver}，开始安装"
-      if [[ ! -n "$new_clash_ver" ]]; then
-        echo -e "${red}Clash检测版本失败!${end}"
-        exit 1
-      fi
-      if [ ! -d "/tmp/clash" ]; then
-        mkdir /tmp/clash
-      fi 
-      webget2 /tmp/clash/clash.gz "${url_cdn}https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-${cpucore}-${new_clash_ver}.gz"
-      if [[ $? -ne 0 ]]; then
-        echo -e "${red}Clash下载失败!${end}"
-        exit 1
-      fi
-      echo -e "${green}Clash下载成功!${end}" 
-      rm -rf /usr/bin/clash
-      gunzip /tmp/clash/clash.gz
-      mv /tmp/clash/clash /usr/bin/clash
-      chmod +x /usr/bin/clash
-      supervisorctl restart clash >> /dev/null 2>&1
-      echo -e "${green}Clash升级成功，请重新运行脚本!${end}" && exit 0
-    fi
-}
-
 install_mosdns() {
 
 # Mosdns core
@@ -1288,40 +1267,6 @@ update_mosdns_y() {
     echo -e "${green}Mosdns has been updated to ${new_mosdns_version}.${end}"
 }
 
-update_mosdns() {
-    #new_mosdns_ver=$(wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep mosdns_v | awk '{print $2}')
-    new_mosdns_ver=$(cat /srv/version  | grep mosdns_v | awk '{print $2}')
-    now_mosdns_ver=$(mosdns -v | awk '{print $1}'| cut -d'-' -f1)
-    if [[ "${now_mosdns_ver}" != "${new_mosdns_ver}" ]]  ;then
-      echo -e "Mosdns已有新版本: ${new_mosdns_ver}，当前版本:${now_mosdns_ver}，开始安装"
-      if [[ ! -n "$new_mosdns_ver" ]]; then
-        echo -e "${red}Mosdns检测版本失败!${end}"
-        exit 1
-      fi
-      if [ ! -d "/tmp/mosdns" ]; then
-        mkdir /tmp/mosdns
-      fi         
-      webget2  /tmp/mosdns/mosdns.zip "${url_cdn}https://github.com/IrineSistiana/mosdns/releases/download/${new_mosdns_ver}/mosdns-linux-${cpucore2}.zip"
-      #[ "$result" != "200" ] && echo "文件下载失败！" && exit 1
-      if [[ $? -ne 0 ]]; then
-        echo -e "${red}Mosdns下载失败!${end}"
-        exit 1
-      fi
-      echo -e "${green}Mosdns下载成功!${end}" 
-      cd /tmp/mosdns
-      rm -rf /usr/bin/mosdns
-      rm -rf /srv/mosdns/config.yaml
-      webget2 /srv/mosdns/config.yaml "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/mosdns/config.yaml"  
-      echo -e "${green}config.yaml下载成功${end}"	
-      unzip /tmp/mosdns/mosdns.zip  >> /dev/null 2>&1
-      mv /tmp/mosdns/mosdns /usr/bin/mosdns
-      chmod 777 /usr/bin/mosdns
-      rm -rf /tmp/mosdns
-      supervisorctl restart mosdns >> /dev/null 2>&1
-      echo -e "${green}Mosdns升级成功，请重新运行脚本!${end}" && exit 0
-    fi
-}
-
 install_subconverter() {
 
 # Subconverter core
@@ -1405,78 +1350,55 @@ install_subconverter() {
 }
 
 update_subconverter_y() {
-    #new_subconverter_ver=$(wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep subconverter_v | awk '{print $2}')
-    new_subconverter_ver=$(cat /srv/version  | grep subconverter_v | awk '{print $2}')
-    if [[ ! -n "$new_subconverter_ver" ]]; then
-      echo -e "${red}Subconverter检测版本失败!${end}"
-      exit 1
+    if [ ! -f "${subconverter_version_file}" ]; then
+      echo 0 > ${subconverter_version_file}
     fi
-    if [ ! -d "/tmp/subconverter" ]; then
-      mkdir /tmp/subconverter
-    fi         
-    webget2  /tmp/subconverter/subconverter.tar.gz "${url_cdn}https://github.com/tindy2013/subconverter/releases/download/${new_subconverter_ver}/subconverter_${cpucore3}.tar.gz"
-    if [[ $? -ne 0 ]]; then
-      echo -e "${red}Subconverter下载失败!${end}"
-      exit 1
-    fi
-    echo -e "${green}Subconverter下载成功!${end}" 
-    cd /tmp/subconverter
-    rm -rf /srv/subconverter/subconverter
-    rm -rf /srv/subconverter/all_base.tpl
-    rm -rf /srv/subconverter/profiles/Loyalsoldier.ini
-    rm -rf /srv/subconverter/profiles/yuanlam.ini
-    webget2 /srv/subconverter/base/all_base.tpl "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/all_base.tpl"  
-    echo -e "${green}all_base.tpl下载成功${end}"
-    webget2 /srv/subconverter/profiles/Loyalsoldier.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/Loyalsoldier.ini"  
-    echo -e "${green}Loyalsoldier.ini下载成功${end}"	
-    webget2 /srv/subconverter/profiles/yuanlam.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/yuanlam.ini"  
-    echo -e "${green}yuanlam.ini下载成功${end}"
-    tar zxvf subconverter.tar.gz >> /dev/null 2>&1
-    mv /tmp/subconverter/subconverter/subconverter /srv/subconverter/subconverter
-    chmod 777 /srv/subconverter/subconverter
-    rm -rf /tmp/subconverter
-    supervisorctl restart subconverter >> /dev/null 2>&1
-    echo -e "${green}Subconverter升级成功，请重新运行脚本!${end}" && exit 0
-}
+    local_subconverter_version=$(cat "${subconverter_version_file}")
 
-update_subconverter() {
-    #new_subconverter_ver=$(wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep subconverter_v | awk '{print $2}')
-    new_subconverter_ver=$(cat /srv/version  | grep subconverter_v | awk '{print $2}')
-    now_subconverter_ver=$(subconverter -v | awk '{print $1}'| cut -d'-' -f1)
-    if [[ "${now_subconverter_ver}" != "${new_subconverter_ver}" ]]  ;then
-      echo -e "Subconverter已有新版本: ${new_subconverter_ver}，当前版本:${now_subconverter_ver}，开始安装"
-      if [[ ! -n "$new_subconverter_ver" ]]; then
-        echo -e "${red}Subconverter检测版本失败!${end}"
-        exit 1
-      fi
-      if [ ! -d "/tmp/subconverter" ]; then
-        mkdir /tmp/subconverter
-      fi         
-      webget2  /tmp/subconverter/subconverter.tar.gz "${url_cdn}https://github.com/tindy2013/subconverter/releases/download/${new_subconverter_ver}/subconverter_${cpucore3}.tar.gz"
-      #[ "$result" != "200" ] && echo "文件下载失败！" && exit 1
-      if [[ $? -ne 0 ]]; then
-        echo -e "${red}Subconverter下载失败!${end}"
-        exit 1
-      fi
-      echo -e "${green}Subconverter下载成功!${end}" 
-      cd /tmp/subconverter
-      rm -rf /srv/subconverter/subconverter
-      rm -rf /srv/subconverter/all_base.tpl
-      rm -rf /srv/subconverter/profiles/Loyalsoldier.ini
-      rm -rf /srv/subconverter/profiles/yuanlam.ini
-      webget2 /srv/subconverter/base/all_base.tpl "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/all_base.tpl"  
-      echo -e "${green}all_base.tpl下载成功${end}"
-      webget2 /srv/subconverter/profiles/Loyalsoldier.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/Loyalsoldier.ini"  
-      echo -e "${green}Loyalsoldier.ini下载成功${end}"	
-      webget2 /srv/subconverter/profiles/yuanlam.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/yuanlam.ini"  
-      echo -e "${green}yuanlam.ini下载成功${end}"
-      tar zxvf subconverter.tar.gz >> /dev/null 2>&1
-      mv /tmp/subconverter/subconverter/subconverter /srv/subconverter/subconverter
-      chmod 777 /srv/subconverter/subconverter
-      rm -rf /tmp/subconverter
-      supervisorctl restart subconverter >> /dev/null 2>&1
-      echo -e "${green}Subconverter升级成功，请重新运行脚本!${end}" && exit 0
+    subconverter_release_download_url="https://api.github.com/repos/tindy2013/subconverter/releases/latest"
+    [ -f /tmp/subconverter_release.json ] && rm /tmp/subconverter_release.json
+    webget2 /tmp/subconverter_release.json "${subconverter_release_download_url}"
+    if [ ! -f /tmp/subconverter_release.json ]; then
+      echo -e "${red}Failed to get the release information of Subconverter.${end}"
+      exit 1
     fi
+
+    remote_subconverter_version=$(jq '.name' /tmp/subconverter_release.json | tr -d '"' | tr -d 'v')
+    if (verlt "${local_subconverter_version}" "${remote_subconverter_version}") then
+      echo -e "${green}Found a new version of Subconverter.${end}"
+    else
+      echo -e "${green}Subconverter is up to date.${end}"
+      exit 2
+    fi
+
+    remote_subconverter_download_url=$(jq '.assets[0].browser_download_url' /tmp/subconverter_release.json | tr -d '"')
+    rm /tmp/subconverter_release.json
+    echo "Start download Subconverter v${remote_subconverter_version} from ${remote_subconverter_download_url}..."
+    [ -f "/tmp/subconverter.tar.gz" ] && rm "/tmp/subconverter.tar.gz"
+    curl -L -# -o "/tmp/subconverter.tar.gz" "${url_cdn}${remote_subconverter_download_url}"
+    if [ ! -f "/tmp/subconverter.tar.gz" ]; then
+      echo -e "${red}Failed to download subconverter.${end}"
+      exit 1
+    fi
+
+    [ -d "/tmp/subconverter" ] && rm -rf "/tmp/subconverter"
+    mkdir "/tmp/subconverter"
+    cd /tmp
+    tar -zxvf /tmp/subconverter.tar.gz >> /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+      echo -e "${red}Failed to download subconverter.${end}"
+      rm /tmp/subconverter.tar.gz
+      rm -rf /tmp/subconverter
+      exit 1
+    fi
+    rm /tmp/subconverter.tar.gz
+    [ -d "${subconverter_bin}" ] && rm -rf "${subconverter_bin}"
+    mv subconverter/subconverter ${subconverter_bin}
+    chmod 777 ${subconverter_bin}
+    rm -rf /tmp/subconverter
+
+    echo "${remote_subconverter_version}" > "${subconverter_version_file}"
+    echo -e "${green}Subconverter has been updated.${end}"
 }
 
 update_shell_y() {
@@ -1575,7 +1497,6 @@ check_mosdns_ver() {
 check_subconverter_ver() {
     new_subconverter_ver=$(wget -qO- https://api.github.com/repos/tindy2013/subconverter/releases | grep '"name": ' | sed -E 's/.*"([^"]+)".*/\1/' | head -n 1)
     #new_subconverter_ver=$(wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep subconverter_v | awk '{print $2}')
-    now_subconverter_ver=$(subconverter -v | awk '{print $1}'| cut -d'-' -f1)
     sed -i  's/'subconverter_v'/'"subconverter_v ${new_subconverter_ver}"'/g'  /srv/version
 }
 
@@ -1584,9 +1505,9 @@ check_ver() {
     check_clash_ver
     check_mosdns_ver
     check_subconverter_ver
-    update_clash
-    update_mosdns
-    update_subconverter
+    # update_clash
+    # update_mosdns
+    # update_subconverter
 }
 
 check_clash_status2() {
@@ -1976,9 +1897,6 @@ show_menu() {
     show_status
     echo -e "———————————————————————————"
     update_shell
-    # update_clash
-    # update_mosdns
-    # update_subconverter
     check_disk_status
     echo -e "${yellow}Internet:   ${end}${local_ip} > ${ipv4}"     
     echo -e "${yellow}Clash:      ${end}$(clash -v | awk '{print $2}') >  ${new_clash_ver}"
