Update aioclash

diff --git a/aioclash b/aioclash
--- a/aioclash
+++ b/aioclash
@@ -23,7 +23,7 @@ purpleb="\033[1;35m"
 lightblue="\033[0;36m"
 lightblueb="\033[1;36m"
 
-sh_ver="1.1.0"
+sh_ver="1.2.0"
 
 url_cdn="https://git.o8.cx/"
 
@@ -88,6 +88,31 @@ webget2(){
     wget $progress $redirect $certificate $timeout -O $1 $2 
     [ $? -eq 0 ] && result="200"
     fi
+}
+
+croncmd(){
+	if [ -n "$(crontab -h 2>&1 | grep '\-l')" ];then
+		crontab $1
+	else
+		crondir="$(crond -h 2>&1 | grep -oE 'Default:.*' | awk -F ":" '{print $2}')"
+		[ ! -w "$crondir" ] && crondir="/etc/storage/cron/crontabs"
+		[ ! -w "$crondir" ] && crondir="/var/spool/cron/crontabs"
+		[ ! -w "$crondir" ] && crondir="/var/spool/cron"
+		[ ! -w "$crondir" ] && echo "你的设备不支持定时任务配置，脚本大量功能无法启用！"
+		[ "$1" = "-l" ] && cat $crondir/$USER 2>/dev/null
+		[ -f "$1" ] && cat $1 > $crondir/$USER
+	fi
+}
+
+cronset(){
+    # 参数1代表要移除的关键字,参数2代表要添加的任务语句
+    tmpcron=/tmp/cron_$USER
+    croncmd -l > $tmpcron 
+    sed -i "/$1/d" $tmpcron
+    sed -i '/^$/d' $tmpcron
+    echo "$2" >> $tmpcron
+    croncmd $tmpcron
+    rm -f $tmpcron
 }
 
 verlte() {
@@ -1060,7 +1085,7 @@ install_clash() {
     supervisor_clash_config
     supervisorctl update >> /dev/null 2>&1
     supervisorctl restart clash >> /dev/null 2>&1
-    echo -e "${yellow}Clash Install Successfully${end}"
+    echo -e "${yellow}Clash successfully installed${end}"
 }
 
 update_clash_y() {
@@ -1210,7 +1235,7 @@ install_mosdns() {
     supervisor_mosdns_config
     supervisorctl update >> /dev/null 2>&1
     supervisorctl restart mosdns >> /dev/null 2>&1
-    echo -e "${yellow}Mosdns Install Successfully${end}"
+    echo -e "${yellow}Mosdns successfully installed${end}"
 }
 
 update_mosdns_y() {
@@ -1371,11 +1396,20 @@ install_subconverter() {
       exit 1
     fi
 
+# Subconverter ShellClash_Full.ini
+    formyairport_download_url="https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/ShellClash_Full.ini"
+    echo -e "${green}Start download Subconverter ShellClash_Full.ini from ${formyairport_download_url}${end}" 
+    webget2  ${SUBCONVERTER_PATH}/profiles/ShellClash_Full.ini  ${url_cdn}${formyairport_download_url}
+    if [ ! -f "${SUBCONVERTER_PATH}/profiles/ShellClash_Full.ini" ]; then
+      echo -e "${red}Failed to download Subconverter ShellClash_Full.ini.${end}"
+      exit 1
+    fi
+
     rm -rf /tmp/subconverter
     supervisor_subconverter_config
     supervisorctl update >> /dev/null 2>&1
     supervisorctl restart subconverter >> /dev/null 2>&1
-    echo -e "${yellow}Subconverter Install Successfully${end}"
+    echo -e "${yellow}Subconverter successfully installed${end}"
 }
 
 update_subconverter_y() {
@@ -1485,12 +1519,12 @@ install_nftables() {
       mkdir /tmp/nftables
     fi
     mkdir -p /etc/nftables
+    echo -e "${green}Start download nftables file...${end}" 
     webget2 /tmp/nftables/nftables.zip  ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/nftables/nftables.zip >> /dev/null 2>&1
     if [[ $? -ne 0 ]]; then
-      echo -e "${red}Nftables下载失败!${end}"
+      echo -e "${red}Failed to download nftables.${end}"
       exit 1
     fi
-    echo -e "${green}Nftables下载成功!${end}" 
     cd /tmp/nftables
     unzip nftables.zip >> /dev/null 2>&1
     mv /tmp/nftables/nftables/chnroute.nft /etc/nftables/chnroute.nft
@@ -1503,14 +1537,14 @@ install_nftables() {
     systemctl enable nftables.service >> /dev/null 2>&1
     systemctl start nftables.service >> /dev/null 2>&1
     rm -rf /tmp/nftables
-    echo -e "${green}Nftables安装成功!${end}"
+    echo -e "${yellow}Nftables successfully installed${end}"
 }
 
 
 install_cron() {
     cat << EOF > /var/spool/cron/crontabs/root
-*/5 * * * * aioclash ping >/dev/null 2>&1 #每5分钟检测clash端口
-0 5 * * * aioclash check_ver >/dev/null 2>&1 #每天的5点0分更新AIOClash
+*/5 * * * * aioclash ping >/dev/null 2>&1 #每5分钟检测Clash服务端口
+0 5 * * * aioclash check_ver >/dev/null 2>&1 #每天的5点0分更新AIOClash服务
 EOF
     chmod 777 /var/spool/cron/crontabs/root
     crontab /var/spool/cron/crontabs/root
@@ -1640,12 +1674,15 @@ update_subconverter_config () {
     mv /srv/subconverter/base/all_base.tpl /tmp/subconverter_all_base.tpl.`date "+%Y.%m.%d.%H:%M"`
     mv /srv/subconverter/profiles/Loyalsoldier.ini /tmp/subconverter_Loyalsoldier.ini.`date "+%Y.%m.%d.%H:%M"`
     mv /srv/subconverter/profiles/yuanlam.ini /tmp/subconverter_yuanlam.ini.`date "+%Y.%m.%d.%H:%M"`
+    mv /srv/subconverter/profiles/yuanlam.ini /tmp/ShellClash_Full.ini.`date "+%Y.%m.%d.%H:%M"`
     webget2 /srv/subconverter/base/all_base.tpl "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/all_base.tpl"  
     echo -e "${green}all_base.tpl下载成功${end}"
     webget2 /srv/subconverter/profiles/Loyalsoldier.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/Loyalsoldier.ini"  
     echo -e "${green}Loyalsoldier.ini下载成功${end}"  
     webget2 /srv/subconverter/profiles/yuanlam.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/yuanlam.ini"  
     echo -e "${green}yuanlam.ini下载成功${end}"
+    webget2 /srv/subconverter/profiles/ShellClash_Full.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/ShellClash_Full.ini"  
+    echo -e "${green}ShellClash_Full.ini下载成功${end}"
     aioclash restart_subconverter
 }
 
@@ -1657,18 +1694,17 @@ install() {
     getcpucore3
     check_clash_status2    
     if [[ $? == 0 ]]; then
-      echo -e "${green}AIOClash已安装"
+      echo -e "${green}AIOClash已安装${end}"
       exit 1
     else
       echo -----------------------------------------------    
-      echo -e "${green}       AIOClash 一键安装"
-      echo -e "${green}按照提示输入IP,网关,DNS"
+      echo -e "${green}欢迎安装AIOClash${end}"
+      echo -e "${green}按照提示输入IP,网关,DNS${end}"
       # echo -e "${green}dler订阅按照提示输入token"   
       # echo -e "${green}请将config.yaml配置文件上传到/root"  
       check_disk_status
       echo -----------------------------------------------
       update_shell
-
       # dler_config
       config_ip_dns
       config_base
@@ -1678,11 +1714,11 @@ install() {
       install_subconverter
       supervisor_config    
       install_nftables
-      install_cron
+      # install_cron
       echo -----------------------------------------------
-      echo -e "${green}       AIOClash 安装成功"
-      echo -e "${green}Clash配置文件:${yaml_path}"
-      echo -e "${green}Clash控制面板:http://${ip_add}:9090/ui/"
+      echo -e "${green}AIOClash 安装成功${end}"
+      echo -e "${green}Clash配置文件:${yaml_path}${end}"
+      echo -e "${green}Clash控制面板:http://${ip_add}:9090/ui/${end}"
       echo -----------------------------------------------
       reboot_show_menu
     fi  
@@ -1860,36 +1896,40 @@ linkconfig(){
   echo -----------------------------------------------
   echo 1  yuanlam养老版（推荐）
   echo 2  Loyalsoldier+奈飞分流（推荐）
-  echo 3  ACL4SSR通用版无去广告（推荐）
-  echo 4  ACL4SSR精简全能版（推荐）
-  echo 5  ACL4SSR通用版+去广告加强
-  echo 6  ACL4SSR精简版+去广告加强
-  echo 7  ACL4SSR重度全分组+奈飞分流
-  echo 8  ACL4SSR重度全分组+去广告加强
+  echo 3  ShellClash增强版（推荐）
+  echo 4  ACL4SSR通用版无去广告（推荐）
+  echo 5  ACL4SSR精简全能版（推荐）
+  echo 6  ACL4SSR通用版+去广告加强
+  echo 7  ACL4SSR精简版+去广告加强
+  echo 8  ACL4SSR重度全分组+奈飞分流
+  echo 9  ACL4SSR重度全分组+去广告加强
   echo -----------------------------------------------
   read -e -p "请输入对应数字[1-8] > " num
   if [ "$num" = 1 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/yuanlam.ini  
+    setconfig config profiles/yuanlam.ini  
   elif [ "$num" = 2 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/Loyalsoldier.ini
+    setconfig config profiles/Loyalsoldier.ini
   elif [ "$num" = 3 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/ACL4SSR_Online_NoReject.ini
+    setconfig config profiles/ShellClash_Full.ini
   elif [ "$num" = 4 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/ACL4SSR_Online_Mini_MultiMode.ini   
+    setconfig config config/ACL4SSR_Online_NoReject.ini
   elif [ "$num" = 5 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/ACL4SSR_Online_AdblockPlus.ini
+    setconfig config config/ACL4SSR_Online_Mini_MultiMode.ini   
   elif [ "$num" = 6 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/ACL4SSR_Online_Mini_AdblockPlus.ini  
+    setconfig config config/ACL4SSR_Online_AdblockPlus.ini
   elif [ "$num" = 7 ];then
     sed -i '/config=*/'d $formyairport_path
-    setconfig config config/ACL4SSR_Online_Full_Netflix.ini
+    setconfig config config/ACL4SSR_Online_Mini_AdblockPlus.ini  
   elif [ "$num" = 8 ];then
+    sed -i '/config=*/'d $formyairport_path
+    setconfig config config/ACL4SSR_Online_Full_Netflix.ini
+  elif [ "$num" = 9 ];then
     sed -i '/config=*/'d $formyairport_path
     setconfig config config/ACL4SSR_Online_Full_AdblockPlus.ini
   else
@@ -1918,7 +1958,8 @@ getlink(){
           getudp
           linkconfig
           echo -----------------------------------------------
-          echo -e   "\033[44m订阅模版完成，请选择<1.更新配置文件>\033[0m"
+          echo -e   "\033[44m订阅模版完成\033[0m"
+          getyaml
           show_menu
         elif [ "$res" = '0' ]; then
           getlink
@@ -1950,12 +1991,13 @@ keepyaml2(){
     PID=$(pidof clash)
     if [ -f "$PID" ];then
       echo -----------------------------------------------
-      echo -e clash启动失败，还原配置文件
+      echo -e "\033[32mclash启动失败，还原配置文件!\033[0m"
       cp -r $bak_yaml_path $yaml_path
       cp -r $bak_formyairport_path $formyairport_path
       supervisorctl restart clash
     else
       echo -----------------------------------------------
+      echo -e "\033[32mClash服务启动成功!\033[0m"
       echo -e "Clash控制面板:\033[36;4mhttp://${local_ip}:9090/ui/\033[0m"
       echo -----------------------------------------------
     fi
@@ -1970,7 +2012,7 @@ keepyaml(){
       keepyaml2
     else
       echo -----------------------------------------------
-      echo -e "\033[32m创建配置文件失败!请选择<2.生成订阅模版>\033[0m"
+      echo -e "\033[32m创建配置文件失败!\033[0m"
       echo -----------------------------------------------
       rm -rf $new_yaml_path 
       show_menu
@@ -1981,7 +2023,7 @@ getyaml(){
     mkyamlbak  
     echo -e "\033[32m正在创建配置文件\033[0m"
     echo -----------------------------------------------
-    wget "http://127.0.0.1:25500/getprofile?name=profiles/formyairport.ini&token=password" -O $new_yaml_path
+    wget "http://127.0.0.1:25500/getprofile?name=profiles/formyairport.ini&token=password" -O $new_yaml_path >> /dev/null 2>&1
     keepyaml
 }
 
@@ -2062,31 +2104,32 @@ clashcron(){
     echo  -e "\033[33m已添加的定时任务:\033[35m"
     crontab -l | grep -oE ' #.*' 
     echo -e "\033[0m"-----------------------------------------------
-    echo -e " 1 设置\033[33m定时重启\033[0mclash服务"
-    echo -e " 2 设置\033[31m定时停止\033[0mclash服务"
-    echo -e " 3 设置\033[32m定时开启\033[0mclash服务"
+    echo -e " 1 设置\033[33m定时重启\033[0mClash服务"
+    echo -e " 2 设置\033[31m定时停止\033[0mClash服务"
+    echo -e " 3 设置\033[32m定时开启\033[0mClash服务"
     echo -e " 4 设置\033[33m定时更新\033[0m订阅并重启服务"
-    echo -e " 5 设置\033[34m定时检测\033[0mclash端口并重启服务"
-    echo -e " 6 设置\033[36m定时更新\033[0mAIOClash"
+    echo -e " 5 设置\033[34m定时检测\033[0mClash服务端口并重启服务"
+    echo -e " 6 设置\033[36m定时更新\033[0mAIOClash服务"
     echo -----------------------------------------------
     echo -e " 0 返回上级菜单" 
+    echo -----------------------------------------------
     read -e -p "请输入对应数字 > " num
     if [ -z "$num" ]; then 
       errornum
     elif [ "$num" = 0 ]; then
       show_menu
     elif [ "$num" = 1 ]; then
-      cronname=重启clash服务
+      cronname=重启Clash服务
       cronset="supervisorctl restart clash"
       setcron
       clashcron
     elif [ "$num" = 2 ]; then
-      cronname=停止clash服务
+      cronname=停止Clash服务
       cronset="supervisorctl stop clash"
       setcron
       clashcron
     elif [ "$num" = 3 ]; then
-      cronname=开启clash服务
+      cronname=开启Clash服务
       cronset="supervisorctl start clash"
       setcron
       clashcron
@@ -2096,7 +2139,7 @@ clashcron(){
       setcron 
       clashcron
     elif [ "$num" = 5 ]; then 
-      cronname=检测clash端口
+      cronname=检测Clash服务端口
       # cronset="aioclash ping"
       # setcron 
       echo -----------------------------------------------
@@ -2109,7 +2152,7 @@ clashcron(){
       if [ -z "$num" ]; then 
         errornum
       elif [ "$num" = 1 ]; then
-        sed -i '$a\*/5 * * * * aioclash ping >/dev/null 2>&1 #每5分钟检测clash端口' /var/spool/cron/crontabs/root
+        sed -i '$a\*/5 * * * * aioclash ping >/dev/null 2>&1 #每5分钟检测Clash服务端口' /var/spool/cron/crontabs/root
       elif [ "$num" = 9 ]; then
         crontab -l > /tmp/conf && sed -i "/$cronname/d" /tmp/conf && crontab /tmp/conf
         rm -f /tmp/conf
@@ -2118,7 +2161,7 @@ clashcron(){
       fi
       clashcron
     elif [ "$num" = 6 ]; then 
-      cronname=更新AIOClash
+      cronname=更新AIOClash服务
       cronset="aioclash check_ver"
       setcron 
       clashcron
@@ -2368,6 +2411,9 @@ uninstall() {
 
     rm -rf ${AIOCLASH_PATH}/version
     rm -rf ${aioclash_path}
+
+    cronset "Clash服务"
+    cronset "订阅链接"
 
     echo -e "${red}AIOClash 卸载成功!请手动重启系统${end}"
     exit 0
