Update aioclash

diff --git a/aioclash b/aioclash
--- a/aioclash
+++ b/aioclash
@@ -33,15 +33,22 @@ gateway=$(cat /etc/network/interfaces |grep gateway | awk '{print $2}' | head -n
 local_ip=$(ip a 2>&1 | grep -w 'inet' | grep 'global' | grep -E '\ 1(92|0|72|00|1)\.' | sed 's/.*inet.//g' | sed 's/\/[0-9][0-9].*$//g' | head -n 1);
 eth_n=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
 
-CLASH_PATH="/srv/clash"
+AIOCLASH="/srv"
+
+CLASH_PATH="${AIOCLASH}/clash"
 CLASH_CORE_PATH="/usr/bin"
 clash_bin="${CLASH_CORE_PATH}/clash"
 clash_version_file="${CLASH_PATH}/version_clash"
 
-MOSDNS_PATH="/srv/mosdns"
+MOSDNS_PATH="${AIOCLASH}/mosdns"
 MOSDNS_CORE_PATH="/usr/bin"
 mosdns_bin="${MOSDNS_CORE_PATH}/mosdns"
 mosdns_version_file="${MOSDNS_PATH}/version_mosdns"
+
+SUBCONVERTER_PATH="${AIOCLASH}/subconverter"
+SUBCONVERTER_CORE_PATH="/usr/bin"
+subconverter_bin="${SUBCONVERTER_CORE_PATH}/subconverter"
+subconverter_version_file="${SUBCONVERTER_PATH}/version_subconverter"
 
 webget2(){
     #参数【$1】代表下载目录，【$2】代表在线地址
@@ -144,7 +151,7 @@ autostart=true                                              ;在supervisord启�
 startsecs=10                                                ;启动后确认无异常时间
 autorestart=true                                            ;程序退出后自动重启,可选值:[unexpected,true,false]，默认为unexpected，表示进程意外杀死后才重启
 startretries=3                                              ;启动失败自动重试次数，默认是3
-redirect_stderr=true 																				;把stderr重定向到stdout，默认false
+redirect_stderr=true                                        ;把stderr重定向到stdout，默认false
 stdout_logfile_maxbytes=20MB                                ;stdout 日志文件大小，默认50MB
 stdout_logfile_backups = 5                                  ;stdout 日志文件备份数，默认是10
 stdout_logfile=/tmp/clash.log                               ;stdout 日志文件，需要注意当指定目录不存在时无法正常启动，所以需要手动创建目录（supervisord 会自动创建日志文件）
@@ -160,7 +167,7 @@ autostart=true                                              ;在supervisord启�
 startsecs=10                                                ;启动后确认无异常时间
 autorestart=true                                            ;程序退出后自动重启,可选值:[unexpected,true,false]，默认为unexpected，表示进程意外杀死后才重启
 startretries=3                                              ;启动失败自动重试次数，默认是3
-redirect_stderr=true 																				;把stderr重定向到stdout，默认false
+redirect_stderr=true                                        ;把stderr重定向到stdout，默认false
 stdout_logfile_maxbytes=20MB                                ;stdout 日志文件大小，默认50MB
 stdout_logfile_backups = 5                                  ;stdout 日志文件备份数，默认是10
 #stdout_logfile=/tmp/mosdns.log                             ;stdout 日志文件，需要注意当指定目录不存在时无法正常启动，所以需要手动创建目录（supervisord 会自动创建日志文件）
@@ -171,12 +178,13 @@ supervisor_subconverter_config() {
     cat << EOF > /etc/supervisor/conf.d/subconverter.conf
 [program:subconverter]                                      ;管理subconverter进程
 user=root                                                   ;启动进程用户，默认是root
+directory=/usr/bin/subconverter                             ;脚本目录
 command=/srv/subconverter/subconverter                      ;程序启动命令
 autostart=true                                              ;在supervisord启动的时候也自动启动
 startsecs=10                                                ;启动后确认无异常时间
 autorestart=true                                            ;程序退出后自动重启,可选值:[unexpected,true,false]，默认为unexpected，表示进程意外杀死后才重启
 startretries=3                                              ;启动失败自动重试次数，默认是3
-redirect_stderr=true 																				;把stderr重定向到stdout，默认false
+redirect_stderr=true                                        ;把stderr重定向到stdout，默认false
 stdout_logfile_maxbytes=20MB                                ;stdout 日志文件大小，默认50MB
 stdout_logfile_backups = 5                                  ;stdout 日志文件备份数，默认是10
 #stdout_logfile=/tmp/subconverter.log                       ;stdout 日志文件，需要注意当指定目录不存在时无法正常启动，所以需要手动创建目录（supervisord 会自动创建日志文件）
@@ -1206,7 +1214,7 @@ install_mosdns() {
 
 update_mosdns_y() {
     if [ ! -f "${mosdns_bin}" ]; then
-      echo "v1.1.1" > ${mosdns_version_file}
+      echo "v0.0.1" > ${mosdns_version_file}
     fi
 
     if [ ! -f "${mosdns_version_file}" ]; then
@@ -1316,41 +1324,86 @@ update_mosdns() {
 }
 
 install_subconverter() {
-    #new_subconverter_ver=$(wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep subconverter_v | awk '{print $2}')
-    new_subconverter_ver=$(cat /srv/version  | grep subconverter_v | awk '{print $2}')
-    if [[ ! -n "$new_subconverter_ver" ]]; then
-      echo -e "${red}subconverter检测版本失败!${end}"
-      exit 1
-    fi
+
+# Subconverter core
+    subconverter_url="https://api.github.com/repos/tindy2013/subconverter/releases/latest"
+
     if [ ! -d "/tmp/subconverter" ]; then
       mkdir /tmp/subconverter
+    fi
+
+    if [ ! -d "${SUBCONVERTER_PATH}" ]; then
+      mkdir ${SUBCONVERTER_PATH}
     fi 
-      cd /tmp/subconverter
-    if [ ! -d "/srv/subconverter" ]; then
-      mkdir /srv/subconverter
-    fi 
-    webget2  /tmp/subconverter/subconverter.tar.gz "${url_cdn}https://github.com/tindy2013/subconverter/releases/download/${new_subconverter_ver}/subconverter_${cpucore3}.tar.gz"
-    if [[ $? -ne 0 ]]; then
-      echo -e "${red}Subconverter下载失败!${end}"
+
+    echo -e "${green}Get Subconverter release information.${end}"
+    webget2 /tmp/subconverter/subconverter_release.json "${subconverter_url}"
+    if [ ! -f "/tmp/subconverter/subconverter_release.json" ]; then
+        echo -e "${red}Failed to get Subconverter release information.${end}"
+        exit 1
+    fi
+
+    subconverter_download_url=$(jq ".assets[${i}].browser_download_url" /tmp/subconverter/subconverter_release.json | tr -d '"' | grep -m1 ${cpucore3})
+    if [ "${subconverter_download_url}" == "" ]; then
+        echo -e "${red}No compatible Subconverter for your platform.${end}"
+        exit 1
+    fi
+
+    echo -e "${green}Start download Subconverter from ${subconverter_download_url}${end}" 
+    webget2 /tmp/subconverter/subconverter.tar.gz "${url_cdn}${subconverter_download_url}"
+    if [ ! -f "/tmp/subconverter/subconverter.zip" ]; then
+        echo -e "${red}Failed to download Subconverter.${end}"
+        exit 1
+    fi
+
+    cd /tmp/subconverter
+    rm -rf ${subconverter_bin}
+    tar -zxvf subconverter.tar.gz  >> /dev/null 2>&1
+    mv subconverter/subconverter ${subconverter_bin}
+    mv subconverter ${SUBCONVERTER_CORE_PATH}
+    chmod 777 ${subconverter_bin}
+
+# Subconverter all_base.tpl
+    all_base_download_url="https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/all_base.tpl"
+    echo -e "${green}Start download Subconverter All_base.tpl from ${all_base_download_url}${end}" 
+    webget2  ${SUBCONVERTER_PATH}/base/all_base.tpl  ${url_cdn}${all_base_download_url}
+    if [ ! -f "${SUBCONVERTER_PATH}/base/all_base.tpl" ]; then
+      echo -e "${red}Failed to download Subconverter All_base.tpl.${end}"
       exit 1
     fi
-    echo -e "${green}Subconverter下载成功!${end}" 
-    cd /tmp/subconverter
-    rm -rf /usr/bin/subconverter
-    tar zxvf subconverter.tar.gz  -C /srv/ >> /dev/null 2>&1
-    webget2 /srv/subconverter/base/all_base.tpl "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/all_base.tpl"  
-    echo -e "${green}all_base.tpl下载成功${end}"
-    webget2 /srv/subconverter/profiles/Loyalsoldier.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/Loyalsoldier.ini"  
-    echo -e "${green}Loyalsoldier.ini下载成功${end}"	
-    webget2 /srv/subconverter/profiles/yuanlam.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/yuanlam.ini"  
-    echo -e "${green}yuanlam.ini下载成功${end}"
-    webget2 /srv/subconverter/profiles/formyairport.ini "${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/formyairport.ini"  
-    echo -e "${green}formyairport.ini下载成功${end}"		    
+
+# Subconverter Loyalsoldier.ini
+    Loyalsoldier_download_url="https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/Loyalsoldier.ini"
+    echo -e "${green}Start download Subconverter Loyalsoldier.ini from ${Loyalsoldier_download_url}${end}" 
+    webget2  ${SUBCONVERTER_PATH}/profiles/Loyalsoldier.ini  ${url_cdn}${Loyalsoldier_download_url}
+    if [ ! -f "${SUBCONVERTER_PATH}/profiles/Loyalsoldier.ini" ]; then
+      echo -e "${red}Failed to download Subconverter Loyalsoldier.ini.${end}"
+      exit 1
+    fi
+
+# Subconverter yuanlam.ini
+    yuanlam_download_url="https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/yuanlam.ini"
+    echo -e "${green}Start download Subconverter yuanlam.ini from ${yuanlam_download_url}${end}" 
+    webget2  ${SUBCONVERTER_PATH}/profiles/yuanlam.ini  ${url_cdn}${yuanlam_download_url}
+    if [ ! -f "${SUBCONVERTER_PATH}/profiles/yuanlam.ini" ]; then
+      echo -e "${red}Failed to download Subconverter yuanlam.ini.${end}"
+      exit 1
+    fi
+
+# Subconverter formyairport.ini
+    formyairport_download_url="https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/subconverter/formyairport.ini"
+    echo -e "${green}Start download Subconverter formyairport.ini from ${formyairport_download_url}${end}" 
+    webget2  ${SUBCONVERTER_PATH}/profiles/formyairport.ini  ${url_cdn}${formyairport_download_url}
+    if [ ! -f "${SUBCONVERTER_PATH}/profiles/formyairport.ini" ]; then
+      echo -e "${red}Failed to download Subconverter formyairport.ini.${end}"
+      exit 1
+    fi
+
     rm -rf /tmp/subconverter
     supervisor_subconverter_config
     supervisorctl update >> /dev/null 2>&1
     supervisorctl restart subconverter >> /dev/null 2>&1
-    echo -e "${green}Subconverter安装成功!${end}"
+    echo -e "${green}Subconverter Install Successfully${end}"
 }
 
 update_subconverter_y() {
@@ -1387,7 +1440,6 @@ update_subconverter_y() {
     supervisorctl restart subconverter >> /dev/null 2>&1
     echo -e "${green}Subconverter升级成功，请重新运行脚本!${end}" && exit 0
 }
-
 
 update_subconverter() {
     #new_subconverter_ver=$(wget -qO- ${url_cdn}https://raw.githubusercontent.com/gdfsnhsw/aioclash/main/version | grep subconverter_v | awk '{print $2}')
